// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxZKG9G_1CdhyZybHWDgLFGM223VpoIhk',
    appId: '1:31832753832:web:07abee1cea8cfb9b5d649d',
    messagingSenderId: '31832753832',
    projectId: 'authen-56181',
    authDomain: 'authen-56181.firebaseapp.com',
    storageBucket: 'authen-56181.firebasestorage.app',
    measurementId: 'G-SR6D7RZ2TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5x8XjTOUl9yBKDabUgY5oWxPcfRnadaI',
    appId: '1:31832753832:android:d14334be3e4c6e565d649d',
    messagingSenderId: '31832753832',
    projectId: 'authen-56181',
    storageBucket: 'authen-56181.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJkjYgSENT0owBnd3c0DtdO_qguBE_cII',
    appId: '1:31832753832:ios:b73d019454e4947a5d649d',
    messagingSenderId: '31832753832',
    projectId: 'authen-56181',
    storageBucket: 'authen-56181.firebasestorage.app',
    iosBundleId: 'com.example.petproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJkjYgSENT0owBnd3c0DtdO_qguBE_cII',
    appId: '1:31832753832:ios:b73d019454e4947a5d649d',
    messagingSenderId: '31832753832',
    projectId: 'authen-56181',
    storageBucket: 'authen-56181.firebasestorage.app',
    iosBundleId: 'com.example.petproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxZKG9G_1CdhyZybHWDgLFGM223VpoIhk',
    appId: '1:31832753832:web:a4c2e1a9b11de3b95d649d',
    messagingSenderId: '31832753832',
    projectId: 'authen-56181',
    authDomain: 'authen-56181.firebaseapp.com',
    storageBucket: 'authen-56181.firebasestorage.app',
    measurementId: 'G-N0R425YHDB',
  );
}
